version: '3.8'

services:
  postgres: 
    image: postgres:latest
    container_name: postgres_ifreserve
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_ifreserve_data:/var/lib/postgresql/data
volumes:
  postgres_ifreserve_data:
