version: '3.8'

services:
  postgres: 
    image: postgres:latest
    container_name: postgres_ifreserve
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_ifreserve_data:/var/lib/postgresql/data
  api: 
    image: node:alpine
    container_name: node_ifreserve
    restart: always
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    working_dir: /if-reserve-back-end
    volumes:
      - .:/if-reserve-back-end
      - /if-reserve-back-end/node_modules
    command: sh -c "npm i && npx prisma migrate deploy && npm run start"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "${DATABASE_URL}"

volumes:
  postgres_ifreserve_data:
